import type {
  IndicatorCategoryItem,
  EmaIndicatorConfig,
  RsiIndicatorConfig,
  SessionsIndicatorConfig,
  QuartersIndicatorConfig,
} from './types';

export const INDICATOR_CATALOG: IndicatorCategoryItem[] = [
  {
    type: 'QUARTERS',
    name: 'Daye Quarterly Theory',
    category: 'Smart Money / ICT',
    badge: 'Time Cycles',
    shortDesc: 'Siklus waktu kuartal 90-Minute Cycles, Daily Quarters (6 jam), dan Weekly Quarters (AMDX).',
    defaultConfig: {
      id: 'daye-quarters-default',
      type: 'QUARTERS',
      name: 'Daye Quarterly Theory',
      enabled: true,
      color: '#38bdf8',
      plotType: 'bottom_pane',
      show90minCycles: true,
      showDailyQuarters: true,
      showWeeklyQuarters: true,
      showLabels: true,
      historicalCycles: true,
    } as QuartersIndicatorConfig,
  },
  {
    type: 'SESSIONS',
    name: 'FX Market Sessions',
    category: 'Trend',
    badge: 'Sessions',
    shortDesc: 'Sesi pasar utama lengkap Tokyo (00:00-09:00 UTC), London (07:00-16:00 UTC), dan New York (12:00-21:00 UTC).',
    defaultConfig: {
      id: 'sessions-default',
      type: 'SESSIONS',
      name: 'FX Market Sessions',
      enabled: true,
      color: '#8b5cf6',
      sessions: [
        {
          id: 'asia',
          name: 'Tokyo',
          enabled: true,
          startUtc: '00:00',
          endUtc: '09:00',
          bgColor: 'rgba(192, 132, 252, 0.12)',
          showHighLow: true,
          highLowColor: '#c084fc',
        },
        {
          id: 'london',
          name: 'London',
          enabled: true,
          startUtc: '07:00',
          endUtc: '16:00',
          bgColor: 'rgba(56, 189, 248, 0.12)',
          showHighLow: true,
          highLowColor: '#38bdf8',
        },
        {
          id: 'newyork',
          name: 'New York',
          enabled: true,
          startUtc: '12:00',
          endUtc: '21:00',
          bgColor: 'rgba(251, 146, 60, 0.12)',
          showHighLow: true,
          highLowColor: '#fb923c',
        },
      ],
    } as SessionsIndicatorConfig,
  },
  {
    type: 'KILLZONES',
    name: 'ICT Killzones',
    category: 'Smart Money / ICT',
    badge: 'ICT / SMC',
    shortDesc: 'Zona likuiditas ICT: Asian KZ (00:00-04:00), London Open KZ (06:00-09:00), NY Open KZ (11:00-14:00), dan London Close KZ (14:00-16:00 UTC).',
    defaultConfig: {
      id: 'killzones-default',
      type: 'KILLZONES',
      name: 'ICT Killzones',
      enabled: true,
      color: '#ec4899',
      sessions: [
        {
          id: 'asian_kz',
          name: 'Asia Killzone',
          enabled: true,
          startUtc: '00:00',
          endUtc: '04:00',
          bgColor: 'rgba(168, 85, 247, 0.14)',
          showHighLow: true,
          highLowColor: '#a855f7',
        },
        {
          id: 'london_kz',
          name: 'London Open Killzone',
          enabled: true,
          startUtc: '06:00',
          endUtc: '09:00',
          bgColor: 'rgba(14, 165, 233, 0.14)',
          showHighLow: true,
          highLowColor: '#0ea5e9',
        },
        {
          id: 'ny_kz',
          name: 'NY Open Killzone',
          enabled: true,
          startUtc: '11:00',
          endUtc: '14:00',
          bgColor: 'rgba(249, 115, 22, 0.14)',
          showHighLow: true,
          highLowColor: '#f97316',
        },
        {
          id: 'london_close_kz',
          name: 'London Close Killzone',
          enabled: true,
          startUtc: '14:00',
          endUtc: '16:00',
          bgColor: 'rgba(236, 72, 153, 0.14)',
          showHighLow: true,
          highLowColor: '#ec4899',
        },
      ],
    } as any,
  },
  {
    type: 'SESSION_OPENS',
    name: 'Session Opens (Daily, London, NY)',
    category: 'Smart Money / ICT',
    badge: 'Key Opens',
    shortDesc: 'Garis horizontal benchmark harga pembukaan Daily Open (21:00 UTC), London Open (07:00 UTC), NY Open (12:00 UTC), dan Midnight Open (04:00 UTC).',
    defaultConfig: {
      id: 'session-opens-default',
      type: 'SESSION_OPENS',
      name: 'Session Opens',
      enabled: true,
      color: '#38bdf8',
      opens: [
        {
          id: 'forex_daily_open',
          name: 'Daily Open',
          enabled: true,
          timeUtc: '21:00',
          color: '#38bdf8',
          lineStyle: 'dashed',
          lineWidth: 1.5,
        },
        {
          id: 'london_open',
          name: 'London Open',
          enabled: true,
          timeUtc: '07:00',
          color: '#a855f7',
          lineStyle: 'solid',
          lineWidth: 1.5,
        },
        {
          id: 'ny_open',
          name: 'NY Open',
          enabled: true,
          timeUtc: '12:00',
          color: '#f97316',
          lineStyle: 'solid',
          lineWidth: 1.5,
        },
        {
          id: 'midnight_open',
          name: 'Midnight Open',
          enabled: true,
          timeUtc: '04:00',
          color: '#eab308',
          lineStyle: 'dotted',
          lineWidth: 1.5,
        },
      ],
    } as any,
  },
  {
    type: 'MACROS',
    name: 'ICT Macro Windows (IPDA Delivery)',
    category: 'Smart Money / ICT',
    badge: 'ICT Macros',
    shortDesc: 'Jendela algoritma 20-menit ICT IPDA Macro: London Pre-Open (06:33 UTC), NY AM Macros (12:50, 13:50, 14:50 UTC), dan NY PM Macros.',
    defaultConfig: {
      id: 'macros-default',
      type: 'MACROS',
      name: 'ICT Macros',
      enabled: true,
      color: '#10b981',
      sessions: [
        {
          id: 'london_pre_macro',
          name: 'London Pre-Open (02:33 NY)',
          enabled: true,
          startUtc: '06:33',
          endUtc: '07:00',
          bgColor: '#06b6d4',
          fillEnabled: true,
          opacity: 0.18,
          showHighLow: true,
          highLowColor: '#06b6d4',
          borderOpacity: 0.85,
        },
        {
          id: 'london_classic_macro',
          name: 'London Classic (04:03 NY)',
          enabled: true,
          startUtc: '08:03',
          endUtc: '08:30',
          bgColor: '#3b82f6',
          fillEnabled: true,
          opacity: 0.18,
          showHighLow: true,
          highLowColor: '#3b82f6',
          borderOpacity: 0.85,
        },
        {
          id: 'ny_am_macro_1',
          name: 'NY AM Macro 1 (08:50 NY)',
          enabled: true,
          startUtc: '12:50',
          endUtc: '13:10',
          bgColor: '#10b981',
          fillEnabled: true,
          opacity: 0.18,
          showHighLow: true,
          highLowColor: '#10b981',
          borderOpacity: 0.85,
        },
        {
          id: 'ny_am_macro_2',
          name: 'NY AM Macro 2 (09:50 NY - Silver Bullet)',
          enabled: true,
          startUtc: '13:50',
          endUtc: '14:10',
          bgColor: '#f59e0b',
          fillEnabled: true,
          opacity: 0.22,
          showHighLow: true,
          highLowColor: '#f59e0b',
          borderOpacity: 0.9,
        },
        {
          id: 'ny_am_macro_3',
          name: 'NY AM Macro 3 (10:50 NY)',
          enabled: true,
          startUtc: '14:50',
          endUtc: '15:10',
          bgColor: '#ef4444',
          fillEnabled: true,
          opacity: 0.18,
          showHighLow: true,
          highLowColor: '#ef4444',
          borderOpacity: 0.85,
        },
        {
          id: 'ny_pm_macro_1',
          name: 'NY PM Macro 1 (13:10 NY)',
          enabled: false,
          startUtc: '17:10',
          endUtc: '17:40',
          bgColor: '#8b5cf6',
          fillEnabled: true,
          opacity: 0.18,
          showHighLow: true,
          highLowColor: '#8b5cf6',
          borderOpacity: 0.85,
        },
        {
          id: 'ny_pm_macro_2',
          name: 'NY PM Macro 2 (15:15 NY)',
          enabled: false,
          startUtc: '19:15',
          endUtc: '19:45',
          bgColor: '#ec4899',
          fillEnabled: true,
          opacity: 0.18,
          showHighLow: true,
          highLowColor: '#ec4899',
          borderOpacity: 0.85,
        },
      ],
    } as any,
  },
  {
    type: 'EMA',
    name: 'Exponential Moving Average (EMA)',
    category: 'Trend',
    badge: 'Trend',
    shortDesc: 'Rata-rata pergerakan harga eksponensial (EMA 20, 50, 100, 200) untuk membaca arah dan momentum tren.',
    defaultConfig: {
      id: 'ema-default',
      type: 'EMA',
      name: 'EMA (20, 50, 100, 200)',
      enabled: true,
      period: 20,
      source: 'close',
      lineWidth: 2,
      color: '#3b82f6',
      emas: [
        { id: 'ema_1', name: 'EMA 1', enabled: true, period: 20, source: 'close', color: '#3b82f6', lineWidth: 2, lineStyle: 'solid' },
        { id: 'ema_2', name: 'EMA 2', enabled: true, period: 50, source: 'close', color: '#f59e0b', lineWidth: 2, lineStyle: 'solid' },
        { id: 'ema_3', name: 'EMA 3', enabled: true, period: 100, source: 'close', color: '#10b981', lineWidth: 2, lineStyle: 'solid' },
        { id: 'ema_4', name: 'EMA 4', enabled: true, period: 200, source: 'close', color: '#ef4444', lineWidth: 2, lineStyle: 'solid' },
        { id: 'ema_5', name: 'EMA 5', enabled: false, period: 9, source: 'close', color: '#8b5cf6', lineWidth: 1, lineStyle: 'solid' },
      ],
    } as EmaIndicatorConfig,
  },
  {
    type: 'RSI',
    name: 'Relative Strength Index (RSI)',
    category: 'Oscillator',
    badge: 'Momentum',
    shortDesc: 'Osilator momentum overbought (70) dan oversold (30) dengan batas garis median 50.',
    defaultConfig: {
      id: 'rsi-14',
      type: 'RSI',
      name: 'RSI 14',
      enabled: true,
      period: 14,
      source: 'close',
      overbought: 70,
      oversold: 30,
      middle: 50,
      color: '#a855f7',
      bandColor: 'rgba(168, 85, 247, 0.08)',
    } as RsiIndicatorConfig,
  },
];
